services:
  ytshortgen:
    build: .
    image: ytshortgen:latest
    container_name: ytshortgen
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    environment:
      - OUTPUT_DIR
    entrypoint: ["/bin/bash"]
    tty: true
